#!/bin/sh
mysql -u root -p <<EOF
CREATE DATABASE devices;
USE devices;
CREATE TABLE smartphones(id VARCHAR(50) PRIMARY KEY,vendor VARCHAR(50),model VARCHAR(200),flashtool VARCHAR(1024) DEFAULT NULL,blmode VARCHAR(1024) DEFAULT NULL,remotebuild VARCHAR(1024) DEFAULT NULL);
# We currently have our own builds for Nexus 6P and Samsung S5 Neo
INSERT INTO smartphones(id,vendor,model,flashtool,blmode) VALUES('angler','Google','Nexus 6P','AOSP','Volume Down + Power');
INSERT INTO smartphones(id,vendor,model,flashtool,blmode) VALUES('s5neolte','Samsung','S5 Neo','heimdall','Volume Down + Home + Power');
# Devices supported by LineageOS
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('I01WD','Asus','Zenfone 6 (ZS630KL)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('bardock','BQ','Aquaris X','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('bardockpro','BQ','Aquaris X Pro','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('mata','Essential','PH-1','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('FP2','FairPhone','FP2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('shamu','Google','Nexus 6','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('sailfish','Google','Pixel','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('marlin','Google','Pixel XL','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('m8','HTC','One (M8)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('m8d','HTC','One (M8) Dual SIM','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('x2','LeEco','Le Max2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('zl1','LeEco','Le Pro3','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('kuntao','Lenovo','P2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('d802','LG','G2 (International)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('d855','LG','G3 (International)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('h850','LG','G5 (International)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('h990','LG','V20 (Global)','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('surnia','Motorola','Moto E 2015 LTE','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('osprey','Motorola','Moto G 2015','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('merlin','Motorola','Moto G3 Turbo','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('harpia','Motorola','Moto G4 Play','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('evert','Motorola','Moto G6 Plus','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('river','Motorola','Moto G7','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('lake','Motorola','Moto G7 Plus','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('chef','Motorola','Moto One Power','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('victara','Motorola','Moto X 2014','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('lux','Motorola','Moto X Play','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('payton','Motorola','Moto X4','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('griffin','Motorola','Moto Z','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('nash','Motorola','Moto Z2 Force','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('nx563j','Nubia','Z17','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('oneplus2','OnePlus','2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('oneplus3','OnePlus','3/3T','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('enchilada','OnePlus','6','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('fajita','OnePlus','6T','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('guacamoleb','OnePlus','7','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('guacamole','OnePlus','7 Pro','android','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('cheryl','Razer','Phone','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('RMX1801','Realme','2 Pro','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('a3xelte','Samsung','Galaxy A3','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('a5xelte','Samsung','Galaxy A5 (2016)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('crownlte','Samsung','Galaxy Note 9','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('jfltexx','Samsung','Galaxy S4 (GT-I9505/G, SGH_I337M, SGH-M919)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('jfltevzw','Samsung','Galaxy S4 (SCH-I545)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('jfltespr','Samsung','Galaxy S4 (SCH-R970, SPH-L720)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('jflteatt','Samsung','Galaxy S4 (SGH-I337)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('jfvelte','Samsung','Galaxy A4 Value Edition (GT-I9515/L)','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('starlte','Samsung','Galaxy S9','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,flashtool,remotebuild) VALUES('star2lte','Samsung','Galaxy S9+','heimdall','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('kirin','Sony','Xperia 10','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('mermaid','Sony','Xperia 10 Plus','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('pioneer','Sony','Xperia XA2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('voyager','Sony','Xperia XA2 Plus','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('discovery','Sony','Xperia XA2 Ultra','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('crackling','Wileyfox','Swift','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('wt88047','Wingtech','Redmi 2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('gemini','Xiaomi','Mi 5','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('natrium','Xiaomi','Mi 5s Plus','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('sagit','Xiaomi','Mi 6','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('wayne','Xiaomi','Mi 6X','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('dipper','Xiaomi','Mi 8','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('jasmine_sprout','Xiaomi','Mi A2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('lithium','Xiaomi','Mi MIX','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('chiron','Xiaomi','Mi MIX 2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('polaris','Xiaomi','Mi MIX 2S','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('scorpio','Xiaomi','Mi Note 2','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('jason','Xiaomi','Mi Note 3','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('beryllium','Xiaomi','Poco F1','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('onclite','Xiaomi','Redmi 7','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('whyred','Xiaomi','Redmi Note 5 Pro','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('twolip','Xiaomi','Redmi Note 6 Pro','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('lavender','Xiaomi','Redmi Note 7','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('Amber','Yandex','Phone','LineageOS');
INSERT INTO smartphones(id,vendor,model,remotebuild) VALUES('z2_plus','ZUK','Z2 Plus','LineageOS');
CREATE TABLE tablets(id VARCHAR(50) PRIMARY KEY,vendor VARCHAR(50),model VARCHAR(200),flashtool VARCHAR(1024) DEFAULT NULL,remotebuild VARCHAR(1024) DEFAULT NULL);
INSERT INTO tablets(id,vendor,model,flashtool,remotebuild) VALUES('gts28vewifi','Samsung','Galaxy Tab S2 8.0 WiFi','heimdall','LineageOS');
INSERT INTO tablets(id,vendor,model,flashtool,remotebuild) VALUES('dragon','Google','Pixel C','fastboot','LineageOS');
GRANT SELECT ON devices.* TO 'devices'@'localhost' IDENTIFIED BY 'DeviceDB';
EOF
